### ISSUE TITLE
Prettier and ESLint config: once-and-for-all.

### ISSUE THREAD

**Issue by varl** [dhis2/code-style#1]
# Code style in DHIS2

Usage of Prettier is getting more widespread in DHIS2-projects and the configuration is often similar but-not-quite-the-same. I figure it is time to consolidate our Prettier configurations into a single place. 

Since there are many variations of `.prettierrc` floating around I realise that the config I am suggesting won't match a given personal preference. Please bear in mind what Prettier sets out to do:

>By far the biggest reason for adopting Prettier is to stop all the on-going debates over styles.

I am going to leave this topic open for discussion until *2018-08-31*. Comments about practical consequences, e.g. "trailing commas make it easier to add new code" will be taken into account.

After we have landed a configuration for Prettier and ESLint, I will start to roll it out to a few apps as a pilot to flush out some issues and to learn how it can be integrated into the workflows, and after a grace period we can roll it out to all apps; new and old.

# The approach

We have had attempts to create a style guide in the form of ESLint [before](https://github.com/dhis2/eslint-config-dhis2) but since adopting *create react app*, which uses ESLint differently from e.g. how AirBnb use(d), it has fallen out. 

Now, if you take two CRA-apps created at different points in time, they could use different configurations for linting and formatting. So even if we base ourselves around "whatever CRA is doing", we will see our code base diverging over time between apps.

The *code style* approach is familiar (you install a package and add a new script to your `package.json`), but instead it pulls in ESLint configuration from a specific version of the ESLint config for React Apps and combines it with a Prettier configuration.

This way we only need to update the configs in `dhis2/code-style` and then bump the version in our apps to the new version of code-style to get fresh linting and formatting definitions. More on how we can handle this step automatically in the section about automation.

# Automation

Running linting and formatting on apps we are currently working on is one thing, that can be handled as developers go about their business, but at the same time we need to maintain our fleet of old front end applications to make sure that they do not suffer from bitrot.

While Prettier configuration shouldn't change often, the CRA ESLint rules are prone to change between major versions. React 15 will have different lint than React 16.

The automated update strategy for DHIS2 libraries is a separate issue, but in broad terms the strategy is this:

1. the **updater** is aware when a new version of a @dhis2-library is published to NPM
2. it clones all apps which depends on the updated library
3. it updates the dep to the latest version in `package.json`
4. it commits and pushes the change on a new branch to origin
5. it creates a pull request for the change
6. travis builds the branch

As Travis builds the branch the linting and formatting will run and if it passes, then we can just merge the branch and all is good, we can keep our direct dependencies automatically fresh with this approach.

If the build fails on linting errors then manual intervention is required. E.g. if we lint a React 15 app with React 16 lint rules, then we will be able to catch issues automatically and visualise that we have an app we should invest in to bring up to React 16 from React 15.

The same steps apply for d2-ui components, as well as other libraries we create.

# The config

So the **code-style** package is one piece of a broader strategy to manage our suite of apps, as well as a step to consolidate everything that deals with code style into the same place. Right now it uses ESLint and Prettier. Tomorrow we might add another tool like EditorConf. In the future we could seamlessly switch out Prettier for Nicer (® pending) and ESLint for ECMALint (® pending).

## `prettier.config.js`:
```
module.exports = {
    printWidth: 80,
    tabWidth: 4,
    useTabs: false,
    semi: false,
    singleQuote: true,
    trailingComma: "es5",
    bracketSpace: true,
    jsxBracketSameLine: false,
    arrowParens: "avoid",
    rangeStart: 0,
    rangeEnd: Infinity,
    proseWrap: "preserve",
    requirePragma: true,
    insertPragma: true
}
```

## `eslint.config.js`:

```
module.exports = {
    "extends": [
        "prettier",
        "react-app"
    ],
    "rules": {
        "no-console": "off"
    }
}
```

**Comment by varl** [comment]
# Prettier rationale

Link to options: https://prettier.io/docs/en/options.html

#### `printWidth: 80,`
Default setting. Heavy recommendation.

#### `tabWidth: 4,`
Less than 8, more than 2.

#### `useTabs: false,`
Spaces is already established in DHIS2.

#### `semi: false,`
Semi-colons are not necessary, *automatic semicolon injection* in the JS interpreter handles this. Prettier automatically injects `;` for the edge cases. From the docs:

>Only add semicolons at the beginning of lines that may introduce ASI failures.

####  `singleQuote: true,`
Single key press vs. two (Java wishes they had this).

>Quotes in JSX will always be double and ignore this setting.

>If the number of quotes outweighs the other quote, the quote which is less used will be used to format the string - Example: "I'm double quoted" results in "I'm double quoted" and "This \"example\" is single quoted" results in 'This "example" is single quoted'.

#### `trailingComma: "es5",`
Easier to add new items in e.g. a list.

#### `bracketSpace: true,`
Legibility.

#### `jsxBracketSameLine: false,`
Easier to add new props to last line of a JSX tag.

#### `arrowParens: "avoid",`
Why have two extra characters when not necessary?

#### `rangeStart: 0,`
#### `rangeEnd: Infinity,`
Run Prettier on the entire file.

#### `proseWrap: "preserve",`
Default setting.

#### `requirePragma: true,`
#### `insertPragma: true`
These two are among the more interesting, especially since we are adding Prettier to large code bases which would benefit from a more gradual approach. It is also easy to see which files have been formatted and will be formatted by Prettier.

From docs:
>Prettier can restrict itself to only format files that contain a special comment, called a pragma, at the top of the file. This is very useful when gradually transitioning large, unformatted codebases to prettier.

>Prettier can insert a special @format marker at the top of files specifying that the file has been formatted with prettier. This works well when used in tandem with the `--require-pragma` option. If there is already a docblock at the top of the file then this option will add a newline to it with the @format marker.

**Comment by varl** [comment]
Hendrik asked this on Slack:
>```
>requirePragma: true,
>insertPragma: true
>```
>
>So these would be set to false for new projects and true for existing projects for which we introduce Prettier retro-actively?

i'm going to give those options a whirl since i'm not sure of how they will actually behave, but i think it doesn't hurt to have a `@format` marker at the top of each file.We are using *jsdoc* anyway and thus we should already have a doc string at the top. It'll simply look like so:

```/**
 * This class does so-and-so and this-and-that
 * @format
 */
```

or if it prepends the format marker, i'm not sure. doesn't matter anyway if it's automatic.
but it does make it clear about which files are formatted and which aren't, a perk that might not mean a lot practically for individual developers, but it makes it easier for me when keeping track of the broad picture.

**Comment by varl** [comment]
I tested the `requirePragma` and `insertPragma` and I'm leaning towards, `false` and `true` respectively.

If a file has:
```
 /**
 * This class does so-and-so and this-and-that
 */
```

This adds:

```
 /**
 * This class does so-and-so and this-and-that
 *
 * @format
 */
```

If the former is true `@format` needs to be added manually which can get tedious, but would allow us to keep some files, for some reason, outside the formatter.

**Comment by varl** [comment]
The code in this repo is formatted with code-style, so you can take a look at the source files to get a feel for it.

**Comment by varl** [comment]
Time has run up. Closing.

**Comment by ismay** [comment]
I guess I'm late to the party, but I just wanted to mention https://www.npmjs.com/package/eslint-config-airbnb as a good shareable eslint config. Some people don't like it as it's somewhat opinionated. But I've found it quite nice, especially when working with react. It's really actively maintained, and following their recommendations saves you from a lot of common mistakes.

I think it's a bit more extensive than the presets that come with create-react-app, so I'm not sure how that would mix though (if you could bolt it on to the presets bundled with that).

**Comment by varl** [comment]
@ismay Hehe, we used to have a repo called [eslint-config-dhis2](https://github.com/dhis2/graveyard/blob/master/graves/eslint-config-dhis2.tgz) which was basically a wrapper around airbnbs lint standards which we included in our applications. It fell out of favor at some point when CRA was adopted and we've fallen back to using the ESLint rules supplied with it.

At some point we can look into adding ESLint to the `cli-style` tool to automatically do linting as well as prettying, but some care needs to be taken to not go overboard with it. 

There are some aspects of the AirBnB javascript style guide I am at odds with. Their style is a subset of javascript where they whitelist a "safe zone" of the language and draw a line in the sand. I guess that's where the "opinionated" comes in to play. :parasol_on_ground:

**Comment by ismay** [comment]
> At some point we can look into adding ESLint to the `cli-style` tool to automatically do linting as well as prettying, but some care needs to be taken to not go overboard with it.

Ah ok, I was under the impression that this was already running eslint on commit as well.

> There are some aspects of the AirBnB javascript style guide I am at odds with. Their style is a subset of javascript where they whitelist a "safe zone" of the language and draw a line in the sand. I guess that's where the "opinionated" comes in to play.

Yeah that's how it feels to me as well. I initially also disabled some of their rules, but after a while just stuck with their recommendations, out of not wanting to bikeshed too much. Certain things are definitely a bit uncommon, like [preferring `i += 1` over `i++`](https://eslint.org/docs/rules/no-plusplus), but I personally don't mind it.

I have the idea that it's nice for keeping a consistent code-style beyond what prettier can achieve, but it's also very possible that it's a weird preference I have, and absolutely horrible for others, I don't know 😋

**Comment by varl** [comment]
Agreed, and I think ESLint would be a nice thing to ease into once we get cli-style integrated into our apps so we can get some more experience with the automated updating of our dependencies.
