### ISSUE TITLE
top level comments gets mixed

### ISSUE THREAD

**Issue by adeelshahid** [dhis2/code-style#3]
If at the top level I have a comment e.g.

`/* global DHIS_CONFIG, manifest */`

It gets converted into,

```
/**
 * /* global DHIS_CONFIG, manifest
 *
 * @format
 */
```

Correct behavior wud be to pre-pend /** @format */ in a single line above any code if _@format_ is not found

**Comment by varl** [comment]
I disabled the pragmas in #4. If you remove the pragmas they won't be re-added.
